version: '3.9'
services:
  django-app:
    build: .
    container_name: django-backend-todo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ToDoList:/usr/src/app
    ports:
      - 8000:8000
      
